server:
  port: 8082

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: cloudtrip
          uri: lb://CLOUDTRIP
          predicates:
            - Path=/client/**,/trip/**
        - id: cloudticket
          uri: lb://CLOUDTICKET
          predicates:
            - Path=/generateTicket/**
  main:
    web-application-type: reactive
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:8761/eureka
    fetch-registry: true
    register-with-eureka: true