services:
  ticketdb:
    image: postgres:12
    hostname: postgresql
    container_name: postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena
      POSTGRES_DB: ticketdb

    networks:
      - cloudNet
  tripdb:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: 'password'
        MYSQL_DATABASE: 'tripdb'
    ports:
        - '3306:3306'
    networks:
      - cloudNet

  trip_spring:
    image: cloud-trip
    networks:
      - cloudNet
    ports:
     - "8080:8080"
    depends_on:
      - tripdb

  ticket_spring:
    image: cloud-ticket
    networks:
      - cloudNet
    ports:
      - "8081:8081"
    depends_on:
      - ticketdb

  eureka:
    image: eureka-server
    networks:
      - cloudNet
    ports:
      - "8761:8761"

  gateway:
    image: api-gateway
    networks:
      - cloudNet
    ports:
      - "8082:8082"


networks:
  cloudNet:
    driver: bridge