version: '3.7'

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - queue
  kafka-server:
    image: 'bitnami/kafka:latest'
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    networks:
      - queue
    depends_on:
      - zookeeper-server
  kafka-producer:
    image: "kafka/producer:latest"
    networks:
      - queue
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper-server
      - kafka-server
  kafka-consumer:
      image: "kafka/consumer:latest"
      networks:
        - queue
      ports:
        - "8081:8081"
      depends_on:
        - zookeeper-server
        - kafka-server
networks:
  queue:
    driver: bridge